@startditaa

+---------------------+
|class X              |
+---------------------+
|cGRE pointer to vtbl +--> +--------------+
+---------------------+    |vtbl for X    |
|cBLU  x_             |    +--------------+
+---------------------+    |cPNK &X꞉꞉GetX | 
                           +--------------+
                           |cPNK &X꞉꞉~X   | 
                           +--------------+

+---------------------+
|class Y              |
+---------------------+
|cGRE pointer to vtbl +--> +--------------+
+---------------------+    |vtbl for Y    |
|cBLU  x_             |    +--------------+
+---------------------+    |cPNK &Y꞉꞉GetX | 
|cBLU  y_             |    +--------------+
+---------------------+    |cPNK &Y꞉꞉~Y   | 
                           +--------------+
                           |cPNK &Y꞉꞉GetY | 
                           +--------------+

+---------------------+
|class Z              |
+---------------------+
|cGRE pointer to vtbl +--> +--------------+
+---------------------+    |vtbl for Z    |
|cBLU  x_             |    +--------------+
+---------------------+    |cPNK &Z꞉꞉GetX | 
|cBLU  y_             |    +--------------+
+---------------------+    |cPNK &Z꞉꞉~Z   | 
|cBLU  z_             |    +--------------+
+---------------------+    |cPNK &Z꞉꞉GetY | 
                           +--------------+
                           |cPNK &Z꞉꞉GetZ | 
                           +--------------+

@endditaa
# ファイルエンコーディング utf-8
