@startditaa

                    /------------\ 
        manipulate  |            |    use
       +------------+ Controller |<------------+
       |            |            |             |
       |            \------------/             |
       v                                      /-\   
   /-------\                                  \+/   
   |       |                                ---+--- 
   | Model |                                   | User
   |       |                                 +-+-+ 
   \---+---/                                 |   | 
       |               /------\                ^
       |               |      |                |
       +-------------->| View +----------------+
            update     |      |       see
                       \------/

@endditaa
