@startditaa

         expression
+---------------------------+
|                           |
v                           v

      glvalue
+-----------------+
|                 |
V                 v

+--------+--------+---------+
|        |        |         |
| lvalue | xvalue | prvalue |
| cBLU   | cYEL   | cGRE    |
+--------+--------+---------+

         ^                  ^
         |                  |
         +------------------+
                rvalue
@endditaa

