@startditaa
行１
    +---------------+
    |               |
    |      str0     |
    |               |
    +-------+-------+
            |
            V
            nullptr
-=-----------------------------------------------
行２の右辺
                            +---------------+ 
                            |               | 
                            | std꞉꞉string() | 
                            |               | 
                            +-------+-------+    
                                    |
                                    V
                                   +------+        
                                   |"hehe"|
                        +--------- | cGRE |
                        |          +------+
-=--------------------- | -=---------------------
行２の左辺                   |
    +---------------+   |   +---------------+ 
    |               |   |   |               | 
    |      str0     |   |   | std꞉꞉string() | 
    |               |   |   |           cRED| 
    +-------+-------+   |   +-------+-------+    
            |           |           |
            V           |           V
           +------+     |           nullptr
           |"hehe"|<----+
           | cGRE |    move
           +------+
-=-----------------------------------------------
行３
    +---------------+       +-=-------------+ 
    |               |       |               | destructing
    |      str0     |       | std꞉꞉string() | 
    |               |       |           cRED| 
    +-------+-------+       +-------+-------+    
            |                       |
            V                       V
           +------+                 nullptr
           |"hehe"|      
           | cGRE |
           +------+
@endditaa
