@startditaa
行１、行２
    +---------------+       +---------------+ 
    |               |       |               | 
    |      str0     |       |      str1     | 
    |               |       |               | 
    +-------+-------+       +-------+-------+    
            |                       |
            V                       V
            nullptr                +------+        
                       copy        |"hehe"|
                        +--------- | cGRE |
                        |          +------+
-=--------------------- | -=---------------------
行３                      |
    +---------------+   |   +---------------+ 
    |               |   |   |               | 
    |      str0     |   |   |      str1     | 
    |               |   |   |               | 
    +-------+-------+   |   +-------+-------+    
            |           |           |
            V           |           V
           +------+     |           +------+
           |"hehe"|<----+           |"hehe"|
           | cBLU |                 | cGRE |
           +------+                 +------+
@endditaa
