@startditaa
    ステップ3
    +------------------+ +------------------+
    |std꞉꞉shared_ptr＜A＞| |std꞉꞉shared_ptr＜A＞|
    |        a0        | |        a1        |
    +--------+---------+ +--------+---------+
             |                    |
             v                    v
             nullptr              +------+
             |                    | A{1} |
             :                    | cGRE |
             |                    +------+
             |
             | x1 ＝ X{std꞉꞉move(a0)}
    +------+ |           +------+   
    |  x0  | |           |  x1  |   
    +--+---+ |           +--+---+   
       |     |              |
       V     v              |
       +------+<------------+
       | A{0} |
       | cBLU |
       +------+

    -=-----------------------------------
      +-----------------------+-------+
      |A꞉꞉LastConstructedNum()|      1|
      +-----------------------+-------+
      |A꞉꞉LastDestructedNum() |     -1|
      +-----------------------+-------+
@endditaa
