@startditaa
  
         +-=----+
         |  x0  |
         +---+--+
             |
             V
   +-------->+-------+
   |         |Xオブジェクト|
   |         |cGRE y_+---+ y_꞉꞉use_count꞉1 y0がスコープアウトしたため
   |         +-------+   |
   |                     |
   |     +-=----+        |
   |  +--+  y0  |        |
   |  |  +------+        |
   |  |                  |
   |  |      +-----------+
   |  |      |
   |  |      V                  
   |  +----->+-------+
   |         |Yオブジェクト|
   +---------+cBLU x_| x_꞉꞉use_count꞉1 x0がスコープアウトしたため
             +-------+

@endditaa



