@startditaa
    ステップ4
    +------------------+ +------------------+
    |std꞉꞉shared_ptr＜A＞| |std꞉꞉shared_ptr＜A＞|
    |        a0        | |        a1        |
    +--------+---------+ +--------+---------+
             |                    |
             v                    v
             nullptr              nullptr 
                                  |            
                                  :
                                  | x1.Move(a1)
    +------+             +------+ | 
    |  x0  |             |  x1  | | 
    +--+---+             +--+---+ | 
       |                    |     |
       V                    V     v
       +------+             +------+ 
       | A{0} |             | A{1} |
       | cBLU |             | cGRE |
       +------+             +------+

    -=-----------------------------------
      +-----------------------+-------+
      |A꞉꞉LastConstructedNum()|      1|
      +-----------------------+-------+
      |A꞉꞉LastDestructedNum() |     -1|
      +-----------------------+-------+
@endditaa
