@startditaa
    ステップ4
    +-=----+   +-=----+
    |  x0  |   |  x2  | use_count꞉0（参照しているXオブジェクトの数）
    +--+---+   +--+---+ 
       |          |
       V          V
     nullptr    nullptr

    +-=----+   +-=----+
    |  y0  |   |  y2  | use_count꞉0（参照しているYオブジェクトの数）
    +--+---+   +--+---+ 
       |          |
       V          V
     nullptr    nullptr


@endditaa



