@startditaa
    ステップ7
    +------+
    |  x0  |
    +--+---+
       |
       V
       nullptr

    x0からのcopy生成          x0からのmove生成  
    +------+             +------+
    |  x2  |             |  x3  |
    +--+---+             +--+---+
       |                    |
       V                    v
       nullptr              nullptr
       +-=----+
       | A{0} | delete
       |      |
       +------+

    -=-----------------------------------
      +-----------------------+-------+
      |A꞉꞉LastConstructedNum()|      1|
      +-----------------------+-------+
      |A꞉꞉LastDestructedNum() |cPNK  0|
      +-----------------------+-------+
@endditaa
