@startditaa
    ステップ2
    +------+   +------+
    |  x0  |   |  x1  | use_count꞉2（参照しているXオブジェクトの数）
    +--+---+   +--+---+ 
       |          |
       +----------+
       | 
       V 
       +-------+
       |Xオブジェクト|
       |cGRE   |
       +-------+

    +------+   +------+
    |  y0  |   |  y1  | use_count꞉2（参照しているYオブジェクトの数）
    +--+---+   +--+---+ 
       |          |
       +----------+
       | 
       V 
       +-------+
       |Yオブジェクト|
       |cBLU   |
       +-------+

@endditaa


