@startditaa
    ステップ3

    use_count꞉2
    +------+   +------+             +------+  
    |  x0  |   |  x2  |  <-- Move --+  x1  | use_count꞉0
    +--+---+   +--+---+             +--+---+   
       |          |                    |           
       +----------+                    V           
       |                              nullptr
       V                    
       +-------+
       |Xオブジェクト|
       |cGRE   |
       +-------+

    use_count꞉2
    +------+   +------+             +------+        
    |  y0  |   |  y2  |  <-- Move --+  y1  |  use_count꞉0       
    +--+---+   +--+---+             +--+---+         
       |          |                    |            
       +----------+                    V            
       |                              nullptr       
       V 
       +-------+
       |Yオブジェクト|
       |cBLU   |
       +-------+

@endditaa



