@startditaa
    ステップ1
    +-----+
    |  x0 | use_count꞉1（参照しているXオブジェクトの数）
    +--+--+
       |
       V
       +-------+
       |Xオブジェクト|
       |cGRE   |
       +-------+

    +-----+
    |  y0 | use_count꞉1（参照しているYオブジェクトの数）
    +--+--+
       |
       V
       +-------+
       |Yオブジェクト|
       |cBLU   |
       +-------+

@endditaa

