@startditaa
    ステップ2
    +------------------+ +------------------+
    |std꞉꞉shared_ptr＜A＞| |std꞉꞉shared_ptr＜A＞|
    |        a0        | |        a1        |
    +--------+---------+ +--------+---------+
             |                    |
             |                    v
             |                    +------+
             |                    | A{1} |
             |                    | cGRE |
             |                    +------+
    +------+ |
    |  x0  | | x0 ＝ X{a0}
    +--+---+ |
       |     |
       V     v
       +------+
       | A{0} |
       | cBLU |
       +------+

    -=-----------------------------------
      +-----------------------+-------+
      |A꞉꞉LastConstructedNum()|      1|
      +-----------------------+-------+
      |A꞉꞉LastDestructedNum() |     -1|
      +-----------------------+-------+
@endditaa
