@startditaa

    +---------------+--------+
    |               | cBLU   |
    | class Base    | name0_ |
    |               |        |
    +---------------+--------+   

    ---

    +---------------+--------+--------+
    |               | cBLU   | cGRE   |
    | class Derived | name0_ | name1_ |
    |               |        |        |
    +---------------+--------+--------+   
 
@endditaa
