@startditaa

               +----d_array[0]---+----d_array[1]---+
               |                 |                 |
        
    +----------+--------+--------+--------+--------+
    |          | cBLU   | cGRE   | cBLU   | cGRE   |
    | d_array  | name0_ | name1_ | name0_ | name1_ |
    |          |  "0"   |  "1"   |  "2"   |  "3"   |
    +----------+--------+--------+--------+--------+
               ^        ^
               |        |
               &b_ptr[0]|
                        &b_ptr[1]
 
@endditaa
