@startditaa
    +---------------+--------+--------+
    |               | cBLU   | cGRE   | 
    | instance d0   | name0_ | name1_ |
    |               |  "d0"  |  "d0"  |
    +---------------+--------+--------+   
                        |        |
    ---                 |        |
                        v        v
    +---------------+--------+--------+
    |               | cBLU   | cGRE   | 
    | instance d2   | name0_ | name1_ |
    |               |  "d0"  |  "d0"  |
    +---------------+--------+--------+ 
                    ^
                    |
     d2_ref --------+
@endditaa
