@startditaa
    +---------------+--------+--------+
    |               | cBLU   | cGRE   |
    | instance d0   | name0_ | name1_ |
    |               |  "d0"  |  "d0"  |
    +---------------+--------+--------+
         
    ---

    +---------------+--------+--------+
    |               | cBLU   | cGRE   | 
    | instance d1   | name0_ | name1_ |
    |               |  "d1"  |  "d1"  |
    +---------------+--------+--------+   
         
    ---

    +---------------+--------+--------+
    |               | cBLU   | cGRE   | 
    | instance d2   | name0_ | name1_ |
    |               |  "d2"  |  "d2"  |
    +---------------+--------+--------+   
                    ^
                    |
     d2_ref --------+
@endditaa
