@startditaa
    +---------------+--------+--------+
    |               | cBLU   | cGRE   | 
    | instance d1   | name0_ | name1_ |
    |               |  "d1"  |  "d1"  |
    +---------------+--------+--------+   
                        |
    ---                 |
                        v
    +---------------+--------+--------+
    |               | cBLU   | cRED   |
    | instance d2   | name0_ | name1_ |
    |               |  "d1"  |  "d0"  |
    +---------------+--------+--------+
                    ^             ^
                    |             |
     d2_ref --------+             +-=- コピーされないため、"d0"のまま
@endditaa
