@startditaa
    ステップ3
    +------------------+ +------------------+
    |std꞉꞉unique_ptr＜A＞| |std꞉꞉unique_ptr＜A＞|
    |        a0        | |        a1        |
    +--------+---------+ +--------+---------+
             |                    |
             V                    v
             nllptr               nullptr
    +-----+                             :
    |  x  |                             |
    +--+--+                             | x.Move(a1)
       |                                |
       +------------------+             |
                          |             v
       +-=----+           +-----> +------+
       | A{0} | delete            | A{1} |
       | cGRE |                   | cGRE |
       +------+                   +------+

    -=-----------------------------------
      +-----------------------+-------+
      |A꞉꞉LastConstructedNum()|      1|
      +-----------------------+-------+
      |A꞉꞉LastDestructedNum() |cPNK  0|
      +-----------------------+-------+
@endditaa
