@startditaa
    ステップ6
    +------------------+ +-=----------------+
    |std꞉꞉unique_ptr＜A＞| |std꞉꞉unique_ptr＜A＞|
    |        a2        | |        a3        |
    +--------+---------+ +--------+---------+
             |                    |
             V                    v
             nullptr              nullptr
                                  +-=----+
                                  | A{1} | delete
                                  | cGRE |
                                  +------+

    -=-----------------------------------
      +-----------------------+-------+
      |A꞉꞉LastConstructedNum()|      1|
      +-----------------------+-------+
      |A꞉꞉LastDestructedNum() |cPNK  1|
      +-----------------------+-------+
@endditaa
