@startditaa
    ステップ2
    +------------------+ +------------------+
    |std꞉꞉unique_ptr＜A＞| |std꞉꞉unique_ptr＜A＞|
    |        a0        | |        a1        |
    +--------+---------+ +--------+---------+
             |                    |
             V                    v
             nullptr              +------+
             |                    | A{1} |
             |                    | cGRE |
             :                    +------+
    +-----+  |
    |  x  |  |
    +--+--+  | x ＝ X{a0}
       |     |
       V     v
       +------+
       | A{0} |
       | cBLU |
       +------+

    -=-----------------------------------
      +-----------------------+-------+
      |A꞉꞉LastConstructedNum()|      1|
      +-----------------------+-------+
      |A꞉꞉LastDestructedNum() |     -1|
      +-----------------------+-------+
@endditaa
