@startditaa
    ステップ4
    +-----+
    |  x  |
    +--+--+
       |
       +------------------------> nullptr
                                  |
    +------------------+          :
    |std꞉꞉unique_ptr＜A＞|          |
    |        a2        |          |
    +--------+---------+          |
             |                    |
             V                    |
             +------+             | x.Release()
             | A{1} | <-----------+ return rvalue
             | cGRE |
             +------+

    -=-----------------------------------
      +-----------------------+-------+
      |A꞉꞉LastConstructedNum()|      1|
      +-----------------------+-------+
      |A꞉꞉LastDestructedNum() |      0|
      +-----------------------+-------+
@endditaa
