SRCS:=\
    srp_ut.cpp ocp_ut.cpp lsp_ut.cpp dip_ut.cpp dip_pipe.cpp \
    dip_server_ng.cpp dip_client_ng.cpp dip_server_ok.cpp dip_client_ok.cpp

#CPP_VER:= c++17
SHARED:=../../
include $(SHARED)make/env.mk
include $(SHARED)make/example.mk
include $(SHARED)make/gtest.mk
