SRCS:=\
    clone_ut.cpp \
    di_ut.cpp singleton_ut.cpp state_machine_ut.cpp state_machine_new.cpp state_machine_old.cpp \
    template_method_factory_ut.cpp template_method_ut.cpp template_method.cpp \
    proxy_ut.cpp bare_server.cpp bare_server_wrapper.cpp wrapped_server.cpp \
    wrapped_server_proxy.cpp strategy_shipping_ut.cpp \
    find_files_ut.cpp find_files_strategy.cpp find_files_old_style.cpp \
    visitor_ut.cpp visitor.cpp visitor_crtp_ut.cpp \
	factory_shipping_lib.cpp factory_shipping_ut.cpp \
    observer_ut.cpp observer_ng.cpp observer_ok.cpp subject_ng.cpp subject_ok.cpp

CPP_VER:= c++17
SHARED:=../../
include $(SHARED)make/env.mk
include $(SHARED)make/example.mk
include $(SHARED)make/gtest.mk
