#pragma once

#include "stringize.h"

#if (!defined(SUPPRESS_WARN_OFF)) && (!defined(__clang__)) && defined(__GNUC__)

#define SUPPRESS_WARN_GCC_BEGIN _Pragma("GCC diagnostic push")
#define SUPPRESS_WARN_GCC_END _Pragma("GCC diagnostic pop")

#define IGNORE_GCC_DIAGNOSTIC(s) _Pragma(STRINGIZE(GCC diagnostic ignored s))

#define SUPPRESS_WARN_GCC_ARRAY_BOUNDS IGNORE_GCC_DIAGNOSTIC("-Warray-bounds")
#define SUPPRESS_WARN_GCC_BOOL_OP IGNORE_GCC_DIAGNOSTIC("-Wbool-operation\"")
#define SUPPRESS_WARN_GCC_ADDRESS IGNORE_GCC_DIAGNOSTIC("-Waddress")
#define SUPPRESS_WARN_GCC_COMMENT IGNORE_GCC_DIAGNOSTIC("-Wcomment")
#define SUPPRESS_WARN_GCC_CATCH_VALUE IGNORE_GCC_DIAGNOSTIC("-Wcatch-value=")
#define SUPPRESS_WARN_GCC_CONV_NULL IGNORE_GCC_DIAGNOSTIC("-Wconversion-null")
#define SUPPRESS_WARN_GCC_DEL_INCOMP IGNORE_GCC_DIAGNOSTIC("-Wdelete-incomplete")
#define SUPPRESS_WARN_GCC_EMPTY_BODY IGNORE_GCC_DIAGNOSTIC("-Wempty-body")
#define SUPPRESS_WARN_GCC_DEPRECATED IGNORE_GCC_DIAGNOSTIC("-Wdeprecated")
#define SUPPRESS_WARN_GCC_DEPRECATED_COPY IGNORE_GCC_DIAGNOSTIC("-Wdeprecated-copy")
#define SUPPRESS_WARN_GCC_DEPRECATED_DECL IGNORE_GCC_DIAGNOSTIC("-Wdeprecated-declarations")
#define SUPPRESS_WARN_GCC_FORMAT_SEC IGNORE_GCC_DIAGNOSTIC("-Wformat-security")
#define SUPPRESS_WARN_GCC_IGNORE_QUAL IGNORE_GCC_DIAGNOSTIC("-Wignored-qualifiers")
#define SUPPRESS_WARN_GCC_IMPLICIT_INT IGNORE_GCC_DIAGNOSTIC("-Wimplicit-int")
#define SUPPRESS_WARN_GCC_INACCESSIBLE_BASE IGNORE_GCC_DIAGNOSTIC("-Winaccessible-base")
#define SUPPRESS_WARN_GCC_MISLEADING_INDENT IGNORE_GCC_DIAGNOSTIC("-Wmisleading-indentation")
#define SUPPRESS_WARN_GCC_INIT_OVERRIDE IGNORE_GCC_DIAGNOSTIC("-Woverride-init")
#define SUPPRESS_WARN_GCC_MISSING_BRACES IGNORE_GCC_DIAGNOSTIC("-Wmissing-braces")
#define SUPPRESS_WARN_GCC_NON_VIRTUAL_DTOR IGNORE_GCC_DIAGNOSTIC("-Wnon-virtual-dtor")
#define SUPPRESS_WARN_GCC_NARROWING IGNORE_GCC_DIAGNOSTIC("-Wnarrowing")
#define SUPPRESS_WARN_GCC_PARENTHESES IGNORE_GCC_DIAGNOSTIC("-Wparentheses")
#define SUPPRESS_WARN_GCC_NULL_ARITH IGNORE_GCC_DIAGNOSTIC("-Wpointer-arith")
#define SUPPRESS_WARN_GCC_PESSIMIZING_MOVE IGNORE_GCC_DIAGNOSTIC("-Wpessimizing-move")
#define SUPPRESS_WARN_GCC_SHIFT_COUNT_OVERFLOW IGNORE_GCC_DIAGNOSTIC("-Wshift-count-overflow")
#define SUPPRESS_WARN_GCC_SIGN_COMPARE IGNORE_GCC_DIAGNOSTIC("-Wsign-compare")
#define SUPPRESS_WARN_GCC_SIZEOF_ARRAY_ARG IGNORE_GCC_DIAGNOSTIC("-Wsizeof-array-argument")
#define SUPPRESS_WARN_GCC_SIZEOF_POINTER_DIV IGNORE_GCC_DIAGNOSTIC("-Wsizeof-pointer-div")
#define SUPPRESS_WARN_GCC_UNINIT IGNORE_GCC_DIAGNOSTIC("-Wuninitialized")
#define SUPPRESS_WARN_GCC_UNUSED_FUNC IGNORE_GCC_DIAGNOSTIC("-Wunused-function")
#define SUPPRESS_WARN_GCC_UNUSED_LOCAL_TYPEDEF IGNORE_GCC_DIAGNOSTIC("-Wunused-local-typedefs")
#define SUPPRESS_WARN_GCC_UNUSED_LABEL IGNORE_GCC_DIAGNOSTIC("-Wunused-label")
#define SUPPRESS_WARN_GCC_UNUSED_PARAM IGNORE_GCC_DIAGNOSTIC("-Wunused-parameter")
#define SUPPRESS_WARN_GCC_UNUSED_RESULT IGNORE_GCC_DIAGNOSTIC("-Wunused-result")
#define SUPPRESS_WARN_GCC_UNUSED_VAL IGNORE_GCC_DIAGNOSTIC("-Wunused-value")
#define SUPPRESS_WARN_GCC_UNUSED_VAR IGNORE_GCC_DIAGNOSTIC("-Wunused-variable")
#define SUPPRESS_WARN_GCC_USER_DEFINED_LITERAL IGNORE_GCC_DIAGNOSTIC("-Wliteral-suffix")
#define SUPPRESS_WARN_GCC_SWITCH IGNORE_GCC_DIAGNOSTIC("-Wswitch")
#define SUPPRESS_WARN_GCC_SWITCH_BOOL IGNORE_GCC_DIAGNOSTIC("-Wswitch-bool")
#define SUPPRESS_WARN_GCC_CONVERSION_VEXING_PARSE IGNORE_GCC_DIAGNOSTIC("-Wvexing-parse")
#define SUPPRESS_WARN_GCC_WRITE_STR IGNORE_GCC_DIAGNOSTIC("-Wwrite-strings")
#define SUPPRESS_WARN_GCC_ENUM_COMP IGNORE_GCC_DIAGNOSTIC("-Wenum-compare")
#define SUPPRESS_WARN_GCC_EXCEPTIONS IGNORE_GCC_DIAGNOSTIC("-Wexceptions")
#define SUPPRESS_WARN_GCC_UNUSED_BUT_SET_VAR IGNORE_GCC_DIAGNOSTIC("-Wunused-but-set-variable")

// only gcc
#define SUPPRESS_WARN_GCC_DANGLING_ELSE IGNORE_GCC_DIAGNOSTIC("-Wdangling-else")
#define SUPPRESS_WARN_GCC_FORMAT_EQ IGNORE_GCC_DIAGNOSTIC("-Wformat=")
#define SUPPRESS_WARN_GCC_CAST_FUNC_TYPE IGNORE_GCC_DIAGNOSTIC("-Wcast-function-type")
#define SUPPRESS_WARN_GCC_CATCH_ASSIGN IGNORE_GCC_DIAGNOSTIC("-Wcatch-value=")
#define SUPPRESS_WARN_GCC_CLASS_MEMACCESS IGNORE_GCC_DIAGNOSTIC("-Wclass-memaccess")
#define SUPPRESS_WARN_GCC_TYPE_LIMITS IGNORE_GCC_DIAGNOSTIC("-Wtype-limits")
#define SUPPRESS_WARN_GCC_FALLTHROUGH IGNORE_GCC_DIAGNOSTIC("-Wimplicit-fallthrough")
#define SUPPRESS_WARN_GCC_LOCAL_RETURN IGNORE_GCC_DIAGNOSTIC("-Wreturn-local-addr")
#define SUPPRESS_WARN_GCC_MISSING_FIELD_INIT IGNORE_GCC_DIAGNOSTIC("-Wmissing-field-initializers")
#define SUPPRESS_WARN_GCC_NON_NULL_COMP IGNORE_GCC_DIAGNOSTIC("-Wnonnull-compare")
#define SUPPRESS_WARN_GCC_NOT_EFF_CPP IGNORE_GCC_DIAGNOSTIC("-Weffc++")
#define SUPPRESS_WARN_GCC_OVERFLOW IGNORE_GCC_DIAGNOSTIC("-Woverflow")
#define SUPPRESS_WARN_GCC_REORDER IGNORE_GCC_DIAGNOSTIC("-Wreorder")
#define SUPPRESS_WARN_GCC_RETURN_TYPE IGNORE_GCC_DIAGNOSTIC("-Wreturn-type")
#define SUPPRESS_WARN_GCC_SEQ_POINT IGNORE_GCC_DIAGNOSTIC("-Wsequence-point")
#define SUPPRESS_WARN_GCC_SWITCH_RANGE IGNORE_GCC_DIAGNOSTIC("-Wswitch-outside-range")
#define SUPPRESS_WARN_GCC_STRING_OVERFLOW IGNORE_GCC_DIAGNOSTIC("-Wstringop-overflow=")
#define SUPPRESS_WARN_GCC_TERMINATE IGNORE_GCC_DIAGNOSTIC("-Wterminate")

#else

#define SUPPRESS_WARN_GCC_BEGIN
#define SUPPRESS_WARN_GCC_END

#define SUPPRESS_WARN_GCC_ADDRESS
#define SUPPRESS_WARN_GCC_ARRAY_BOUNDS
#define SUPPRESS_WARN_GCC_BOOL_OP
#define SUPPRESS_WARN_GCC_COMMENT
#define SUPPRESS_WARN_GCC_CATCH_VALUE
#define SUPPRESS_WARN_GCC_CONV_NULL
#define SUPPRESS_WARN_GCC_DEL_INCOMP
#define SUPPRESS_WARN_GCC_EMPTY_BODY
#define SUPPRESS_WARN_GCC_DEPRECATED
#define SUPPRESS_WARN_GCC_DEPRECATED_COPY
#define SUPPRESS_WARN_GCC_DEPRECATED_DECL
#define SUPPRESS_WARN_GCC_FORMAT_SEC
#define SUPPRESS_WARN_GCC_IGNORE_QUAL
#define SUPPRESS_WARN_GCC_IMPLICIT_INT
#define SUPPRESS_WARN_GCC_INACCESSIBLE_BASE
#define SUPPRESS_WARN_GCC_MISLEADING_INDENT
#define SUPPRESS_WARN_GCC_INIT_OVERRIDE
#define SUPPRESS_WARN_GCC_MISSING_BRACES
#define SUPPRESS_WARN_GCC_NON_VIRTUAL_DTOR
#define SUPPRESS_WARN_GCC_PARENTHESES
#define SUPPRESS_WARN_GCC_NULL_ARITH
#define SUPPRESS_WARN_GCC_PESSIMIZING_MOVE
#define SUPPRESS_WARN_GCC_SHIFT_COUNT_OVERFLOW
#define SUPPRESS_WARN_GCC_SIGN_COMPARE
#define SUPPRESS_WARN_GCC_SIZEOF_ARRAY_ARG
#define SUPPRESS_WARN_GCC_SIZEOF_POINTER_DIV
#define SUPPRESS_WARN_GCC_UNINIT
#define SUPPRESS_WARN_GCC_UNUSED_FUNC
#define SUPPRESS_WARN_GCC_UNUSED_LOCAL_TYPEDEF
#define SUPPRESS_WARN_GCC_UNUSED_LABEL
#define SUPPRESS_WARN_GCC_UNUSED_PARAM
#define SUPPRESS_WARN_GCC_UNUSED_RESULT
#define SUPPRESS_WARN_GCC_UNUSED_VAL
#define SUPPRESS_WARN_GCC_UNUSED_VAR
#define SUPPRESS_WARN_GCC_USER_DEFINED_LITERAL
#define SUPPRESS_WARN_GCC_CONVERSION_VEXING_PARSE
#define SUPPRESS_WARN_GCC_WRITE_STR
#define SUPPRESS_WARN_GCC_ENUM_COMP_SWITCH

// only gcc
#define SUPPRESS_WARN_GCC_UNUSED_BUT_SET_VAR
#define SUPPRESS_WARN_GCC_DANGLING_ELSE
#define SUPPRESS_WARN_GCC_FORMAT_EQ
#define SUPPRESS_WARN_GCC_CAST_FUNC_TYPE
#define SUPPRESS_WARN_GCC_CATCH_ASSIGN
#define SUPPRESS_WARN_GCC_CLASS_MEMACCESS
#define SUPPRESS_WARN_GCC_DEPRECATED
#define SUPPRESS_WARN_GCC_INACCESSIBLE_BASE
#define SUPPRESS_WARN_GCC_ENUM_COMP
#define SUPPRESS_WARN_GCC_EXCEPTIONS
#define SUPPRESS_WARN_GCC_FALLTHROUGH
#define SUPPRESS_WARN_GCC_INACCESS_BASE
#define SUPPRESS_WARN_GCC_TYPE_LIMITS
#define SUPPRESS_WARN_GCC_LOCAL_RETURN
#define SUPPRESS_WARN_GCC_MISSING_FIELD_INIT
#define SUPPRESS_WARN_GCC_NARROWING
#define SUPPRESS_WARN_GCC_NON_NULL_COMP
#define SUPPRESS_WARN_GCC_NOT_EFF_CPP
#define SUPPRESS_WARN_GCC_OVERFLOW
#define SUPPRESS_WARN_GCC_REORDER
#define SUPPRESS_WARN_GCC_RETURN_TYPE
#define SUPPRESS_WARN_GCC_SEQ_POINT
#define SUPPRESS_WARN_GCC_SWITCH_RANGE
#define SUPPRESS_WARN_GCC_STRING_OVERFLOW
#define SUPPRESS_WARN_GCC_SWITCH
#define SUPPRESS_WARN_GCC_SWITCH_BOOL
#define SUPPRESS_WARN_GCC_TERMINATE

#endif
