#pragma once

#include "stringize.h"

#if (!defined(SUPPRESS_WARN_OFF)) && defined(__clang__)

#define SUPPRESS_WARN_CLANG_BEGIN _Pragma("clang diagnostic push")
#define SUPPRESS_WARN_CLANG_END _Pragma("clang diagnostic pop")

#define IGNORE_CLANG_DIAGNOSTIC(s) _Pragma(STRINGIZE(clang diagnostic ignored s))

#define SUPPRESS_WARN_CLANG_ARRAY_BOUNDS IGNORE_CLANG_DIAGNOSTIC("-Warray-bounds")
#define SUPPRESS_WARN_CLANG_BOOL_OP IGNORE_CLANG_DIAGNOSTIC("-Wbool-operation");
#define SUPPRESS_WARN_CLANG_ADDRESS IGNORE_CLANG_DIAGNOSTIC("-Wtautological-pointer-compare")
#define SUPPRESS_WARN_CLANG_COMMENT IGNORE_CLANG_DIAGNOSTIC("-Wcomment")
#define SUPPRESS_WARN_CLANG_CONV_NULL IGNORE_CLANG_DIAGNOSTIC("-Wconversion-null")
#define SUPPRESS_WARN_CLANG_DEL_INCOMP IGNORE_CLANG_DIAGNOSTIC("-Wdelete-incomplete")
#define SUPPRESS_WARN_CLANG_EMPTY_BODY IGNORE_CLANG_DIAGNOSTIC("-Wempty-body")
#define SUPPRESS_WARN_CLANG_FORMAT_SEC IGNORE_CLANG_DIAGNOSTIC("-Wformat-security")
#define SUPPRESS_WARN_CLANG_IGNORE_QUAL IGNORE_CLANG_DIAGNOSTIC("-Wignored-qualifiers")
#define SUPPRESS_WARN_CLANG_MISLEADING_INDENT IGNORE_CLANG_DIAGNOSTIC("-Wmisleading-indentation")
#define SUPPRESS_WARN_CLANG_DEPRECATED IGNORE_CLANG_DIAGNOSTIC("-Wdeprecated")
#define SUPPRESS_WARN_CLANG_DEPRECATED_COPY IGNORE_CLANG_DIAGNOSTIC("-Wdeprecated-copy")
#define SUPPRESS_WARN_CLANG_DEPRECATED_DECL IGNORE_CLANG_DIAGNOSTIC("-Wdeprecated-declarations")
#define SUPPRESS_WARN_CLANG_IMPLICIT_INT IGNORE_CLANG_DIAGNOSTIC("-Wimplicit-int")
#define SUPPRESS_WARN_CLANG_IMPLICIT_CONST_FLOAT IGNORE_CLANG_DIAGNOSTIC("-Wimplicit-const-int-float-conversion")
#define SUPPRESS_WARN_CLANG_INACCESSIBLE_BASE IGNORE_CLANG_DIAGNOSTIC("-Winaccessible-base")
#define SUPPRESS_WARN_CLANG_INIT_OVERRIDE IGNORE_CLANG_DIAGNOSTIC("-Winitializer-overrides")
#define SUPPRESS_WARN_CLANG_MISSING_BRACES IGNORE_CLANG_DIAGNOSTIC("-Wmissing-braces")
#define SUPPRESS_WARN_CLANG_MISSING_FIELD_INIT IGNORE_CLANG_DIAGNOSTIC("-Wmissing-field-initializers")
#define SUPPRESS_WARN_CLANG_NON_VIRTUAL_DTOR IGNORE_CLANG_DIAGNOSTIC("-Wnon-virtual-dtor")
#define SUPPRESS_WARN_CLANG_NULL_ARITH IGNORE_CLANG_DIAGNOSTIC("-Wnull-arithmetic")
#define SUPPRESS_WARN_CLANG_PARENTHESES IGNORE_CLANG_DIAGNOSTIC("-Wparentheses")
#define SUPPRESS_WARN_CLANG_PESSIMIZING_MOVE IGNORE_CLANG_DIAGNOSTIC("-Wpessimizing-move")
#define SUPPRESS_WARN_CLANG_SHIFT_COUNT_OVERFLOW IGNORE_CLANG_DIAGNOSTIC("-Wshift-count-overflow")
#define SUPPRESS_WARN_CLANG_SIGN_COMPARE IGNORE_CLANG_DIAGNOSTIC("-Wsign-compare")
#define SUPPRESS_WARN_CLANG_SIZEOF_ARRAY_ARG IGNORE_CLANG_DIAGNOSTIC("-Wsizeof-array-argument")
#define SUPPRESS_WARN_CLANG_SIZEOF_POINTER_DIV IGNORE_CLANG_DIAGNOSTIC("-Wsizeof-pointer-div")
#define SUPPRESS_WARN_CLANG_UNINIT IGNORE_CLANG_DIAGNOSTIC("-Wuninitialized")
#define SUPPRESS_WARN_CLANG_UNUSED_FUNC IGNORE_CLANG_DIAGNOSTIC("-Wunused-function")
#define SUPPRESS_WARN_CLANG_UNUSED_LOCAL_TYPEDEF IGNORE_CLANG_DIAGNOSTIC("-Wunused-local-typedefs")
#define SUPPRESS_WARN_CLANG_UNUSED_LABEL IGNORE_CLANG_DIAGNOSTIC("-Wunused-label")
#define SUPPRESS_WARN_CLANG_UNUSED_PARAM IGNORE_CLANG_DIAGNOSTIC("-Wunused-parameter")
#define SUPPRESS_WARN_CLANG_UNUSED_RESULT IGNORE_CLANG_DIAGNOSTIC("-Wunused-result")
#define SUPPRESS_WARN_CLANG_UNUSED_VAR IGNORE_CLANG_DIAGNOSTIC("-Wunused-variable")
#define SUPPRESS_WARN_CLANG_UNUSED_VAL IGNORE_CLANG_DIAGNOSTIC("-Wunused-value")
#define SUPPRESS_WARN_CLANG_USER_DEFINED_LITERAL IGNORE_CLANG_DIAGNOSTIC("-Wuser-defined-literals")
#define SUPPRESS_WARN_CLANG_SWITCH IGNORE_CLANG_DIAGNOSTIC("-Wswitch")
#define SUPPRESS_WARN_CLANG_SWITCH_BOOL IGNORE_CLANG_DIAGNOSTIC("-Wswitch-bool")
#define SUPPRESS_WARN_CLANG_CONVERSION_VEXING_PARSE IGNORE_CLANG_DIAGNOSTIC("-Wvexing-parse")

#define SUPPRESS_WARN_CLANG_ENUM_COMP IGNORE_CLANG_DIAGNOSTIC("-Wenum-compare")
#define SUPPRESS_WARN_CLANG_ENUM_ENUM_COMP_SWITCH IGNORE_CLANG_DIAGNOSTIC("-Wenum-compare-switch")
#define SUPPRESS_WARN_CLANG_UNUSED_BUT_SET_VAR IGNORE_CLANG_DIAGNOSTIC("-Wunused-but-set-variable")
#define SUPPRESS_WARN_CLANG_WRITE_STR IGNORE_CLANG_DIAGNOSTIC("-Wwritable-strings")

// only clang
#define SUPPRESS_WARN_CLANG_CONST_CONV IGNORE_CLANG_DIAGNOSTIC("-Wconstant-conversion")
#define SUPPRESS_WARN_CLANG_DANGLING_GSL IGNORE_CLANG_DIAGNOSTIC("-Wdangling-gsl")
#define SUPPRESS_WARN_CLANG_DEPRECATED_INCREMENT_BOOL IGNORE_CLANG_DIAGNOSTIC("-Wdeprecated-increment-bool")
#define SUPPRESS_WARN_CLANG_EXCEPTIONS IGNORE_CLANG_DIAGNOSTIC("-Wexceptions")
#define SUPPRESS_WARN_CLANG_INCONSISTENT_MISSING_OVERRIDE IGNORE_CLANG_DIAGNOSTIC("-Winconsistent-missing-override")
#define SUPPRESS_WARN_CLANG_LITERAL_CONVERSION IGNORE_CLANG_DIAGNOSTIC("-Wliteral-conversion")
#define SUPPRESS_WARN_CLANG_LOGICAL_OP_PARENTHESES IGNORE_CLANG_DIAGNOSTIC("-Wlogical-op-parentheses")
#define SUPPRESS_WARN_CLANG_MISMATCHED_NEW_DELETE IGNORE_CLANG_DIAGNOSTIC("-Wmismatched-new-delete")
#define SUPPRESS_WARN_CLANG_NARROWING IGNORE_CLANG_DIAGNOSTIC("-Wc++11-narrowing")
#define SUPPRESS_WARN_CLANG_NON_POD_VARARGS IGNORE_CLANG_DIAGNOSTIC("-Wnon-pod-varargs")
#define SUPPRESS_WARN_CLANG_OVERLOADED_VIRTUAL IGNORE_CLANG_DIAGNOSTIC("-Woverloaded-virtual")
#define SUPPRESS_WARN_CLANG_POINTER_BOOL_CONVERSION IGNORE_CLANG_DIAGNOSTIC("-Wpointer-bool-conversion")
#define SUPPRESS_WARN_CLANG_POTENTIALLY_EVALUATED_EXPRESSION \
    IGNORE_CLANG_DIAGNOSTIC("-Wpotentially-evaluated-expression")
#define SUPPRESS_WARN_CLANG_REINTERPRET_BASE_CLASS IGNORE_CLANG_DIAGNOSTIC("-Wreinterpret-base-class")
#define SUPPRESS_WARN_CLANG_REORDER_CTOR IGNORE_CLANG_DIAGNOSTIC("-Wreorder-ctor")
#define SUPPRESS_WARN_CLANG_RESERVED_USER_DEFINED_LITERAL IGNORE_CLANG_DIAGNOSTIC("-Wreserved-user-defined-literal")
#define SUPPRESS_WARN_CLANG_RETURN_STACK_ADDRESS IGNORE_CLANG_DIAGNOSTIC("-Wreturn-stack-address")
#define SUPPRESS_WARN_CLANG_RETURN_TYPE IGNORE_CLANG_DIAGNOSTIC("-Wreturn-type")
#define SUPPRESS_WARN_CLANG_SELF_ASSIGN_OVERLOADED IGNORE_CLANG_DIAGNOSTIC("-Wself-assign-overloaded")
#define SUPPRESS_WARN_CLANG_SELF_MOVE IGNORE_CLANG_DIAGNOSTIC("-Wself-move")
#define SUPPRESS_WARN_CLANG_UNDEFINED_INTERNAL IGNORE_CLANG_DIAGNOSTIC("-Wundefined-internal")
#define SUPPRESS_WARN_CLANG_UNDEF_COMP IGNORE_CLANG_DIAGNOSTIC("-Wtautological-undefined-compare")
#define SUPPRESS_WARN_CLANG_OVERLAP_COMP IGNORE_CLANG_DIAGNOSTIC("-Wtautological-overlap-compare")
#define SUPPRESS_WARN_CLANG_INT_FLOAT_CONVERSION IGNORE_CLANG_DIAGNOSTIC("-Wimplicit-const-int-float-conversion")

#define SUPPRESS_WARN_CLANG_UNEVALUATED_EXPRESSION IGNORE_CLANG_DIAGNOSTIC("-Wunevaluated-expression")
#define SUPPRESS_WARN_CLANG_VARARGS IGNORE_CLANG_DIAGNOSTIC("-Wvarargs")
#define SUPPRESS_WARN_CLANG_UNKNOWN_ESCAPE_SEQUENCE IGNORE_CLANG_DIAGNOSTIC("-Wunknown-escape-sequence")
#define SUPPRESS_WARN_CLANG_UNSEQUENCED IGNORE_CLANG_DIAGNOSTIC("-Wunsequenced")
#define SUPPRESS_WARN_CLANG_UNUSED_CONST_VAR IGNORE_CLANG_DIAGNOSTIC("-Wunused-const-variable")
#define SUPPRESS_WARN_CLANG_UNUSED_INTERNAL_DECL IGNORE_CLANG_DIAGNOSTIC("-Wunneeded-internal-declaration")
#define SUPPRESS_WARN_CLANG_UNUSED_PRIVATE_FIELD IGNORE_CLANG_DIAGNOSTIC("-Wunused-private-field")
#define SUPPRESS_WARN_CLANG_UNUSED_CAPTURE IGNORE_CLANG_DIAGNOSTIC("-Wunused-lambda-capture")
#define SUPPRESS_WARN_CLANG_ENUM_COMP_SWITCH IGNORE_CLANG_DIAGNOSTIC("-Wenum-compare-switch")

#else

#define SUPPRESS_WARN_CLANG_BEGIN
#define SUPPRESS_WARN_CLANG_END

#define SUPPRESS_WARN_CLANG_ADDRESS
#define SUPPRESS_WARN_CLANG_ARRAY_BOUNDS
#define SUPPRESS_WARN_CLANG_BOOL_OP
#define SUPPRESS_WARN_CLANG_ENUM_COMP
#define SUPPRESS_WARN_CLANG_ENUM_ENUM_COMP_SWITCH
#define SUPPRESS_WARN_CLANG_UNUSED_BUT_SET_VAR
#define SUPPRESS_WARN_CLANG_WRITE_STR
#define SUPPRESS_WARN_CLANG_COMMENT
#define SUPPRESS_WARN_CLANG_CONV_NULL
#define SUPPRESS_WARN_CLANG_DEL_INCOMP
#define SUPPRESS_WARN_CLANG_EMPTY_BODY
#define SUPPRESS_WARN_CLANG_FORMAT_SEC
#define SUPPRESS_WARN_CLANG_IGNORE_QUAL
#define SUPPRESS_WARN_CLANG_MISLEADING_INDENT
#define SUPPRESS_WARN_CLANG_DEPRECATED_COPY
#define SUPPRESS_WARN_CLANG_DEPRECATED_DECL
#define SUPPRESS_WARN_CLANG_IMPLICIT_INT
#define SUPPRESS_WARN_CLANG_IMPLICIT_CONST_FLOAT
#define SUPPRESS_WARN_CLANG_INACCESSIBLE_BASE
#define SUPPRESS_WARN_CLANG_INIT_OVERRIDE
#define SUPPRESS_WARN_CLANG_MISSING_BRACES
#define SUPPRESS_WARN_CLANG_MISSING_FIELD_INIT
#define SUPPRESS_WARN_CLANG_NON_VIRTUAL_DTOR
#define SUPPRESS_WARN_CLANG_NULL_ARITH
#define SUPPRESS_WARN_CLANG_PARENTHESES
#define SUPPRESS_WARN_CLANG_PESSIMIZING_MOVE
#define SUPPRESS_WARN_CLANG_SHIFT_COUNT_OVERFLOW
#define SUPPRESS_WARN_CLANG_SIGN_COMPARE
#define SUPPRESS_WARN_CLANG_SIZEOF_ARRAY_ARG
#define SUPPRESS_WARN_CLANG_SIZEOF_POINTER_DIV
#define SUPPRESS_WARN_CLANG_UNINIT
#define SUPPRESS_WARN_CLANG_UNUSED_FUNC
#define SUPPRESS_WARN_CLANG_UNUSED_LOCAL_TYPEDEF
#define SUPPRESS_WARN_CLANG_UNUSED_LABEL
#define SUPPRESS_WARN_CLANG_UNUSED_PARAM
#define SUPPRESS_WARN_CLANG_UNUSED_RESULT
#define SUPPRESS_WARN_CLANG_UNUSED_VAL
#define SUPPRESS_WARN_CLANG_UNUSED_VAR
#define SUPPRESS_WARN_CLANG_USER_DEFINED_LITERAL
#define SUPPRESS_WARN_CLANG_SWITCH
#define SUPPRESS_WARN_CLANG_SWITCH_BOOL

// only clang
#define SUPPRESS_WARN_CLANG_CONVERSION_VEXING_PARSE
#define SUPPRESS_WARN_CLANG_CONST_CONV
#define SUPPRESS_WARN_CLANG_DANGLING_GSL
#define SUPPRESS_WARN_CLANG_DEPRECATED_INCREMENT_BOOL
#define SUPPRESS_WARN_CLANG_EXCEPTIONS
#define SUPPRESS_WARN_CLANG_INCONSISTENT_MISSING_OVERRIDE
#define SUPPRESS_WARN_CLANG_LITERAL_CONVERSION
#define SUPPRESS_WARN_CLANG_LOGICAL_OP_PARENTHESES
#define SUPPRESS_WARN_CLANG_MISMATCHED_NEW_DELETE
#define SUPPRESS_WARN_CLANG_NARROWING
#define SUPPRESS_WARN_CLANG_NON_POD_VARARGS
#define SUPPRESS_WARN_CLANG_OVERLOADED_VIRTUAL
#define SUPPRESS_WARN_CLANG_POINTER_BOOL_CONVERSION
#define SUPPRESS_WARN_CLANG_POTENTIALLY_EVALUATED_EXPRESSION
#define SUPPRESS_WARN_CLANG_REINTERPRET_BASE_CLASS
#define SUPPRESS_WARN_CLANG_REORDER_CTOR
#define SUPPRESS_WARN_CLANG_RESERVED_USER_DEFINED_LITERAL
#define SUPPRESS_WARN_CLANG_RETURN_STACK_ADDRESS
#define SUPPRESS_WARN_CLANG_RETURN_TYPE
#define SUPPRESS_WARN_CLANG_SELF_ASSIGN_OVERLOADED
#define SUPPRESS_WARN_CLANG_SELF_MOVE
#define SUPPRESS_WARN_CLANG_UNDEFINED_INTERNAL
#define SUPPRESS_WARN_CLANG_UNDEF_COMP
#define SUPPRESS_WARN_CLANG_OVERLAP_COMP
#define SUPPRESS_WARN_CLANG_INT_FLOAT_CONVERSION
#define SUPPRESS_WARN_CLANG_UNEVALUATED_EXPRESSION
#define SUPPRESS_WARN_CLANG_VARARGS
#define SUPPRESS_WARN_CLANG_UNKNOWN_ESCAPE_SEQUENCE
#define SUPPRESS_WARN_CLANG_UNSEQUENCED
#define SUPPRESS_WARN_CLANG_UNUSED_CONST_VAR
#define SUPPRESS_WARN_CLANG_UNUSED_INTERNAL_DECL
#define SUPPRESS_WARN_CLANG_UNUSED_PRIVATE_FIELD
#define SUPPRESS_WARN_CLANG_UNUSED_CAPTURE
#define SUPPRESS_WARN_CLANG_ENUM_COMP_SWITCH

#endif
